version: "3.1"

services:
    app:
        build: ./app
        environment:
            SPOTIFY_CLIENT_ID: ${SPOTIPY_CLIENT_ID}
            SPOTIFY_CLIENT_SECRET: ${SPOTIPY_CLIENT_SECRET}
            SPOTIFY_OAUTH_TOKEN: ${SPOTIFY_OAUTH_TOKEN}
            POSTGRES_USER: ${POSTGRES_USER-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-example}
            POSTGRES_DB: ${POSTGRES_DB-spotify}
            POSTGRES_HOST: ${POSTGRES_HOST-db}
        # volumes:
        # - ./app/src:/app
        ports:
            - 8083:8083
        depends_on:
            - db
            - broker

    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /pgdata
        volumes:
            - ./pgdata:/pgdata

    adminer:
        image: adminer:4.8.1
        restart: always
        ports:
            - 8080:8080

    broker:
        image: rabbitmq:3.9.13-management-alpine
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER-guest}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS-guest}
        ports:
            - 15672:15672
            - 5672:5672
