version: "3.1"

services:
    www:
        build: ./www
        restart: always
        ports:
            - 3001:3001
        logging:
            driver: fluentd
            options:
                tag: "grabt.{{.ID}}"
        depends_on:
            - api
            - fluentd

    app:
        build: ./app
        environment:
            SPOTIFY_CLIENT_ID: ${SPOTIPY_CLIENT_ID}
            SPOTIFY_CLIENT_SECRET: ${SPOTIPY_CLIENT_SECRET}
            POSTGRES_USER: ${POSTGRES_USER-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-example}
            POSTGRES_DB: ${POSTGRES_DB-spotify}
            POSTGRES_HOST: ${POSTGRES_HOST-db}
            SPOTIPY_REDIRECT_URI: ${SPOTIPY_REDIRECT_URI:-http://127.0.0.1:8083/}
        # volumes:
        # - ./app/src:/app
        ports:
            - 8083:8083
        logging:
            driver: fluentd
            options:
                tag: "grabt.{{.ID}}"
        depends_on:
            - db
            - broker
            - fluentd

    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /pgdata
        volumes:
            - ./pgdata:/pgdata
            - ../spotify-grabtrack-backups:/pg_backup
        logging:
            driver: fluentd
            options:
                tag: "grabt.{{.ID}}"
        depends_on:
            - fluentd

    adminer:
        image: adminer:4.8.1
        restart: always
        ports:
            - 8080:8080
        logging:
            driver: fluentd
            options:
                tag: "grabt.{{.ID}}"
        depends_on:
            - fluentd

    broker:
        image: rabbitmq:3.9.13-management-alpine
        hostname: ${RABBITMQ_HOSTNAME-grabtrack_broker}
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER-guest}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS-guest}
            RABBITMQ_MNESIA_DIR: /rabbitmq_mnesia_dir
        volumes:
            - ./rabbitmq_mnesia_dir:/rabbitmq_mnesia_dir
        ports:
            - 15672:15672
            - 5672:5672
        logging:
            driver: fluentd
            options:
                tag: "grabt.{{.ID}}"
        depends_on:
            - fluentd

    api:
        image: postgrest/postgrest
        restart: always
        ports:
            - 3000:3000
        environment:
            PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB-spotify}
            PGRST_DB_SCHEMA: public
            PGRST_DB_ANON_ROLE: ${POSTGRES_USER} #In production this role should not be the same as the one used for the connection
            PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
        logging:
            driver: fluentd
            options:
                tag: "grabt.{{.ID}}"
        depends_on:
            - db
            - fluentd

    redis:
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./redis_cache:/data
            - ./conf/redis.conf:/conf/redis.conf
        command: redis-server /conf/redis.conf
        logging:
            driver: fluentd
            options:
                tag: "grabt.{{.ID}}"
        depends_on:
            - fluentd

    redisinsights:
        image: redislabs/redisinsight:latest
        restart: always
        ports:
            - 8001:8001
        logging:
            driver: fluentd
            options:
                tag: "grabt.{{.ID}}"
        depends_on:
            - fluentd

    # fluentd:
    #     build: ./fluentd
    #     ports:
    #         - 24224:24224
