version: "3.1"

services:
    www:
        build: ./www
        ports:
            - 3001:3001
        depends_on:
            - api

    app:
        build: ./app
        environment:
            SPOTIFY_CLIENT_ID: ${SPOTIPY_CLIENT_ID}
            SPOTIFY_CLIENT_SECRET: ${SPOTIPY_CLIENT_SECRET}
            POSTGRES_USER: ${POSTGRES_USER-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-example}
            POSTGRES_DB: ${POSTGRES_DB-spotify}
            POSTGRES_HOST: ${POSTGRES_HOST-db}
            SPOTIPY_REDIRECT_URI: ${SPOTIPY_REDIRECT_URI:-http://127.0.0.1:8083/}
        # volumes:
        # - ./app/src:/app
        ports:
            - 8083:8083
        depends_on:
            - db
            - broker

    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /pgdata
        volumes:
            - ./pgdata:/pgdata
            - ../spotify-grabtrack-backups:/pg_backup

    adminer:
        image: adminer:4.8.1
        restart: always
        ports:
            - 8080:8080

    broker:
        image: rabbitmq:3.9.13-management-alpine
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER-guest}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS-guest}
        ports:
            - 15672:15672
            - 5672:5672

    api:
        image: postgrest/postgrest
        ports:
            - 3000:3000
        environment:
            PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB-spotify}
            PGRST_DB_SCHEMA: public
            PGRST_DB_ANON_ROLE: ${POSTGRES_USER} #In production this role should not be the same as the one used for the connection
            PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
        depends_on:
            - db

    redis:
        image: redis:latest
        ports:
            - 6397:6397
        volumes:
            - ./redis_cache:/data
            - ./conf/redis.conf:/conf/redis.conf
        command: redis-server /conf/redis.conf
